# Generated by Django 4.2.1 on 2023-07-03 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followed_by_user',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='followers_of_user',
            field=models.IntegerField(default=0),
        ),
    ]
